# DEBUG処理用
import logging

#祝日設定用
import datetime

"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oiu-n52ks)@wu89&k^a@wkm(d%0x-ie5@x^y7o+#b=0(pql!&j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'app.apps.AppConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# 東京のタイムゾーンに設定
TIME_ZONE = 'Asia/Tokyo'

# タイムゾーンを使用するかどうか
USE_TZ = True

#ログイン処理後の遷移先画面の指定
LOGIN_REDIRECT_URL = 'app:base_list'
#ログアウト処理後の遷移先画面の指定
LOGOUT_REDIRECT_URL = 'accounts:login'

# DEBUGログ出力用
if DEBUG:
    # will output to your console
    logging.basicConfig(
        level = logging.DEBUG,
        format = '%(asctime)s %(levelname)s %(message)s',
    )
else:
    # will output to logging file
    logging.basicConfig(
        level = logging.DEBUG,
        format = '%(asctime)s %(levelname)s %(message)s',
        filename = '/my_log_file.log',
        filemode = 'a'
    )

# CSS使用のための設定(開発段階)
STATIC_URL = '/static/'

#祝日設定用
PUBLIC_HOLIDAYS = [
    # 2022
    datetime.date(year=2022, month=1, day=1),
    datetime.date(year=2022, month=1, day=13),
    datetime.date(year=2022, month=2, day=11),
    datetime.date(year=2022, month=2, day=23),
    datetime.date(year=2022, month=2, day=24),
    datetime.date(year=2022, month=3, day=20),
    datetime.date(year=2022, month=4, day=29),
    datetime.date(year=2022, month=5, day=3),
    datetime.date(year=2022, month=5, day=4),
    datetime.date(year=2022, month=5, day=5),
    datetime.date(year=2022, month=7, day=20),
    datetime.date(year=2022, month=8, day=11),
    datetime.date(year=2022, month=9, day=21),
    datetime.date(year=2022, month=9, day=22),
    datetime.date(year=2022, month=10, day=12),
    datetime.date(year=2022, month=11, day=3),
    datetime.date(year=2022, month=11, day=23),

    # 2023
    datetime.date(year=2023, month=1, day=1),
    datetime.date(year=2023, month=1, day=11),
    datetime.date(year=2023, month=2, day=11),
    datetime.date(year=2023, month=2, day=23),
    datetime.date(year=2023, month=3, day=20),
    datetime.date(year=2023, month=4, day=29),
    datetime.date(year=2023, month=5, day=3),
    datetime.date(year=2023, month=5, day=4),
    datetime.date(year=2023, month=5, day=5),
    datetime.date(year=2023, month=7, day=19),
    datetime.date(year=2023, month=8, day=11),
    datetime.date(year=2023, month=9, day=20),
    datetime.date(year=2023, month=9, day=23),
    datetime.date(year=2023, month=10, day=11),
    datetime.date(year=2023, month=11, day=3),
    datetime.date(year=2023, month=11, day=23),
]
