# Generated by Django 4.1.3 on 2022-11-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_schedule_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.DateField(verbose_name='予約日'),
        ),
    ]
