# Generated by Django 4.1.3 on 2022-11-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_schedule_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.DateTimeField(verbose_name='予約日'),
        ),
    ]
