# Generated by Django 4.1.3 on 2022-11-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_schedule_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='start',
            new_name='date',
        ),
    ]
