# Generated by Django 4.1.3 on 2022-11-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_schedule_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('date', 'base', 'seat'), name='schedule_unique'),
        ),
    ]
